/* eslint-disable @typescript-eslint/no-use-before-define */
/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useState} from 'react';
import {StyleSheet, Text, View, TouchableOpacity} from 'react-native';
import Netify from 'react-native-netify';

Netify.init({
  timeout: 60,
});

export default function App() {
  const [response, setResponse] = useState('');

  function handleGetRequest() {
    Netify.jsonRequest({
      url: 'http://dummy.restapiexample.com/api/v1/employees',
      method: 'get',
      headers: {
        'Content-Type': 'application/json',
      },
    })
      .then((response) => {
        setResponse(JSON.stringify(response));
      })
      .catch(handleError);
  }

  function handlePostRequest() {
    Netify.jsonRequest({
      url: 'http://dummy.restapiexample.com/api/v1/create',
      method: 'post',
      headers: {
        'Content-Type': 'application/json',
      },
      body: {
        name: 'test',
        salary: '123',
        age: '23',
      },
    })
      .then((response) => {
        setResponse(JSON.stringify(response));
      })
      .catch(handleError);
  }

  function handleError(error: any) {
    const {
      response: {status, headers, data},
    } = error;
    console.log(status, headers, data);
  }

  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆Netify example☆</Text>
      <TouchableOpacity style={styles.button} onPress={handleGetRequest}>
        <Text>GET request</Text>
      </TouchableOpacity>
      <TouchableOpacity style={styles.button} onPress={handlePostRequest}>
        <Text>POST request</Text>
      </TouchableOpacity>
      <Text style={styles.welcome}>☆ Response ☆</Text>
      <Text style={styles.instructions} numberOfLines={5}>
        {response}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  button: {
    backgroundColor: 'green',
    padding: 10,
    margin: 15,
  },
});
